global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "payjoin-directory"
    static_configs:
      - targets: ["localhost:3000"] # Adjust based on payjoin-directory port
  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]
